// Seed data for HomeInventory

const CATALOGS = [
  {
    id: "sneakers",
    name: "Sneakers",
    owner: "David",
    description: "Everyday rotation, grails, and boxes in the closet.",
    coverTone: "oklch(0.78 0.05 45)",
    fields: ["Brand", "Model", "Colorway", "Size", "Tags"],
    itemCount: 24,
  },
  {
    id: "decor",
    name: "Christmas Decor",
    owner: "Sarah",
    description: "Ornaments, lights, and heirlooms — boxed in the attic.",
    coverTone: "oklch(0.8 0.04 140)",
    fields: ["Name", "Tags"],
    itemCount: 47,
  },
  {
    id: "clothing",
    name: "Clothing",
    owner: "David",
    description: "Seasonal wardrobe and archival pieces.",
    coverTone: "oklch(0.82 0.03 250)",
    fields: ["Brand", "Item", "Size", "Tags"],
    itemCount: 112,
  },
];

const ITEMS = [
  // --- Sneakers ---
  {
    id: "snk-01",
    catalogId: "sneakers",
    name: "Air Max 1",
    subtitle: "USA Anniversary",
    brand: "Nike",
    model: "Air Max 1",
    colorway: "White / Red / Royal",
    size: "US 10",
    tags: ["running", "og", "rotation"],
    acquired: "2024-03",
    tone: "oklch(0.88 0.02 30)",
    accentTone: "oklch(0.62 0.16 25)",
    stripeAngle: 15,
    photoLabel: "AM1 · 3/4",
  },
  {
    id: "snk-02",
    catalogId: "sneakers",
    name: "Samba OG",
    subtitle: "Cloud White",
    brand: "Adidas",
    model: "Samba OG",
    colorway: "White / Core Black / Gum",
    size: "US 10",
    tags: ["everyday", "rotation"],
    acquired: "2024-01",
    tone: "oklch(0.92 0.01 90)",
    accentTone: "oklch(0.3 0.01 60)",
    stripeAngle: 90,
    photoLabel: "Samba · side",
  },
  {
    id: "snk-03",
    catalogId: "sneakers",
    name: "New Balance 990v6",
    subtitle: "Made in USA",
    brand: "New Balance",
    model: "990v6",
    colorway: "Grey",
    size: "US 10",
    tags: ["dad", "rotation", "comfort"],
    acquired: "2023-11",
    tone: "oklch(0.78 0.01 240)",
    accentTone: "oklch(0.55 0.02 240)",
    stripeAngle: 60,
    photoLabel: "990v6",
  },
  {
    id: "snk-04",
    catalogId: "sneakers",
    name: "Dunk Low",
    subtitle: "Panda",
    brand: "Nike",
    model: "Dunk Low",
    colorway: "Black / White",
    size: "US 10",
    tags: ["everyday"],
    acquired: "2023-06",
    tone: "oklch(0.95 0 0)",
    accentTone: "oklch(0.22 0 0)",
    stripeAngle: 135,
    photoLabel: "Dunk",
  },
  {
    id: "snk-05",
    catalogId: "sneakers",
    name: "Jordan 4",
    subtitle: "Military Blue",
    brand: "Jordan",
    model: "Air Jordan 4 Retro",
    colorway: "White / Military Blue / Neutral Grey",
    size: "US 10",
    tags: ["grails", "archive"],
    acquired: "2024-05",
    tone: "oklch(0.9 0.02 240)",
    accentTone: "oklch(0.42 0.1 255)",
    stripeAngle: 45,
    photoLabel: "AJ4 · side",
  },
  {
    id: "snk-06",
    catalogId: "sneakers",
    name: "Clarks Wallabee",
    subtitle: "Maple Suede",
    brand: "Clarks",
    model: "Wallabee",
    colorway: "Maple",
    size: "US 10",
    tags: ["casual", "rotation"],
    acquired: "2023-09",
    tone: "oklch(0.78 0.06 60)",
    accentTone: "oklch(0.55 0.08 50)",
    stripeAngle: 100,
    photoLabel: "Wallabee",
  },
  {
    id: "snk-07",
    catalogId: "sneakers",
    name: "Gazelle Indoor",
    subtitle: "Bliss Pink",
    brand: "Adidas",
    model: "Gazelle Indoor",
    colorway: "Bliss Pink / Cream",
    size: "US 10",
    tags: ["rotation"],
    acquired: "2024-02",
    tone: "oklch(0.88 0.05 20)",
    accentTone: "oklch(0.72 0.1 20)",
    stripeAngle: 120,
    photoLabel: "Gazelle",
  },
  {
    id: "snk-08",
    catalogId: "sneakers",
    name: "Salomon XT-6",
    subtitle: "Phantom",
    brand: "Salomon",
    model: "XT-6",
    colorway: "Phantom / Black",
    size: "US 10",
    tags: ["trail", "technical"],
    acquired: "2023-12",
    tone: "oklch(0.4 0.01 250)",
    accentTone: "oklch(0.25 0.01 250)",
    stripeAngle: 75,
    photoLabel: "XT-6",
  },
  {
    id: "snk-09",
    catalogId: "sneakers",
    name: "Converse Chuck 70",
    subtitle: "Black Hi",
    brand: "Converse",
    model: "Chuck 70 Hi",
    colorway: "Black / Egret",
    size: "US 10",
    tags: ["og", "rotation"],
    acquired: "2022-08",
    tone: "oklch(0.28 0 0)",
    accentTone: "oklch(0.92 0 0)",
    stripeAngle: 30,
    photoLabel: "Chuck 70",
  },
  {
    id: "snk-10",
    catalogId: "sneakers",
    name: "Asics GT-2160",
    subtitle: "Cream / Cilantro",
    brand: "Asics",
    model: "GT-2160",
    colorway: "Cream / Cilantro",
    size: "US 10",
    tags: ["rotation", "running"],
    acquired: "2024-04",
    tone: "oklch(0.92 0.02 90)",
    accentTone: "oklch(0.58 0.1 140)",
    stripeAngle: 55,
    photoLabel: "GT-2160",
  },
  {
    id: "snk-11",
    catalogId: "sneakers",
    name: "Onitsuka Mexico 66",
    subtitle: "White / Blue",
    brand: "Onitsuka Tiger",
    model: "Mexico 66",
    colorway: "White / Blue",
    size: "US 10",
    tags: ["casual"],
    acquired: "2023-05",
    tone: "oklch(0.93 0.01 230)",
    accentTone: "oklch(0.48 0.13 250)",
    stripeAngle: 25,
    photoLabel: "Mexico 66",
  },
  {
    id: "snk-12",
    catalogId: "sneakers",
    name: "Merrell 1TRL",
    subtitle: "Moab Mythos",
    brand: "Merrell",
    model: "1TRL Moab",
    colorway: "Olive / Tan",
    size: "US 10",
    tags: ["trail", "archive"],
    acquired: "2024-06",
    tone: "oklch(0.68 0.06 120)",
    accentTone: "oklch(0.48 0.08 90)",
    stripeAngle: 110,
    photoLabel: "Moab",
  },

  // --- Christmas Decor ---
  {
    id: "dec-01",
    catalogId: "decor",
    name: "Grandma's glass birds",
    tags: ["tree", "heirloom", "fragile"],
    acquired: "inherited",
    tone: "oklch(0.88 0.05 160)",
    accentTone: "oklch(0.68 0.1 180)",
    stripeAngle: 45,
    photoLabel: "glass birds",
  },
  {
    id: "dec-02",
    catalogId: "decor",
    name: "Ceramic village — 6 pc set",
    tags: ["mantle", "village"],
    tone: "oklch(0.92 0.02 80)",
    accentTone: "oklch(0.72 0.06 60)",
    stripeAngle: 135,
    photoLabel: "village",
  },
  {
    id: "dec-03",
    catalogId: "decor",
    name: "Outdoor warm-white lights — 200ft",
    tags: ["outdoor", "lights"],
    tone: "oklch(0.95 0.04 90)",
    accentTone: "oklch(0.82 0.08 85)",
    stripeAngle: 0,
    photoLabel: "lights",
  },
  {
    id: "dec-04",
    catalogId: "decor",
    name: "Hand-stitched stockings (4)",
    tags: ["mantle", "fabric"],
    tone: "oklch(0.7 0.1 25)",
    accentTone: "oklch(0.45 0.12 20)",
    stripeAngle: 90,
    photoLabel: "stockings",
  },
  {
    id: "dec-05",
    catalogId: "decor",
    name: "Nutcracker, tall",
    tags: ["decor", "heirloom"],
    tone: "oklch(0.72 0.12 30)",
    accentTone: "oklch(0.38 0.1 25)",
    stripeAngle: 60,
    photoLabel: "nutcracker",
  },
  {
    id: "dec-06",
    catalogId: "decor",
    name: "Wreath — cedar & eucalyptus",
    tags: ["outdoor", "wreath"],
    tone: "oklch(0.68 0.08 140)",
    accentTone: "oklch(0.5 0.1 130)",
    stripeAngle: 20,
    photoLabel: "wreath",
  },
  {
    id: "dec-07",
    catalogId: "decor",
    name: "Tree topper — brass star",
    tags: ["tree", "heirloom"],
    tone: "oklch(0.85 0.08 85)",
    accentTone: "oklch(0.65 0.12 75)",
    stripeAngle: 45,
    photoLabel: "brass star",
  },
  {
    id: "dec-08",
    catalogId: "decor",
    name: "Vintage tin ornaments (12)",
    tags: ["tree", "vintage"],
    tone: "oklch(0.78 0.04 45)",
    accentTone: "oklch(0.58 0.08 40)",
    stripeAngle: 135,
    photoLabel: "tin orn.",
  },
  {
    id: "dec-09",
    catalogId: "decor",
    name: "Advent calendar — wooden",
    tags: ["advent", "wood"],
    tone: "oklch(0.72 0.06 55)",
    accentTone: "oklch(0.48 0.08 45)",
    stripeAngle: 75,
    photoLabel: "advent",
  },
];

window.CATALOGS = CATALOGS;
window.ITEMS = ITEMS;
